services:
  database:
    image: postgres
    container_name: database
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - pgdata:/data/postgres

  api:
    build: .
    container_name: nutritionAi_api
    restart: always
    ports:
      - 3001:3001
    volumes:
      - .:/usr/app
      - /usr/app/node_modules
      - /usr/app/prisma
    environment:
      DATABASE_URL: "${DATABASE_URL}"
    links:
      - database
    depends_on:
      - database

volumes:
  pgdata:
    driver: local
